
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqedcaxtvonpjrdzwnxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxZWRjYXh0dm9ucGpyZHp3bnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTI2NzY0NzcsImV4cCI6MjAyODI1MjQ3N30.Yd_6UO8X_XYjbRI1h1r-WrVQVL-iQn7HKjYgSZoiCQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    db: {
      schema: 'public',
    },
  }
);
